/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fedx

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test
    fun appIsTrue() {
        assertTrue(true)
    }
}
